### ISSUE TITLE
Download available?

### ISSUE THREAD

**Issue by starzonmyarmz** [Shuyinsama/Splitr#1]
Sorry to open a GH issue for something like this, but is there a demo/beta available for Splitr. Desperately looking for a _real_ Mac Time Split App!

**Comment by Shuyinsama** [comment]
My apologies but at the moment this timer is still not in a usable state.

Sadly I won't be able to work on this for quite a while due to work and moving into a new house later this month.

Again my apologies.

Kind Regards
Patrick

**Comment by starzonmyarmz** [comment]
No problem! Been there myself! Best of luck!
